### ISSUE TITLE
[BUG] App is Getting crash as soon as we run ( iOS )

### ISSUE THREAD

**Issue by UttamPanchasara** [Canardoux/tau#587] opened 2021-01-15 13:42 UTC
## Flutter Sound Version : 7.5.1+2

----------------------------------------------------------

## Severity

- Crash? : Yes App getting crash

- Minor issue ?: NO
--------------------------------------------------------

## Platforms you faced the error 

- iOS ? yes 

- Android ? no

- Real device ? yes

----------------------------------------------

## Logs

Here is the crash logs we are getting:
Assertion failed: (flutterSoundPlayerManager == nil), function +[FlutterSoundPlayerManager registerWithRegistrar:], file /Users/uttam/.pub

------------------------------------------------
**Describe the bug**
Application is getting crash as soon as we run:

Here is the logs :
Assertion failed: (flutterSoundPlayerManager == nil), function +[FlutterSoundPlayerManager registerWithRegistrar:], file /Users/uttam/.pub

**To Reproduce**
Just use the plugin to record the audio stream, and when try to run app on iOS getting crash, even the plugin methods is not yet triggered.

Have tried both version light and normal both having same problem please fix.

Is there any configuration that we need to setup for iOS to work?

**Comment by Larpoux** [comment] 2021-01-15 14:11
It seems that the plugin is plugged several times.
Did you do something special with your Podfile ?

**Comment by Larpoux** [comment] 2021-01-15 14:12
Do you use Hot Restart ?

**Comment by UttamPanchasara** [comment] 2021-01-18 06:13
No nothing special, No hot-restart, Plugin is added once and It's working fine on Android but when we try to run same on iOS app is got crash as soon as launched.

**Comment by Larpoux** [comment] 2021-01-18 14:52
This is a duplicate of #411 .

Please add your comments in this thread.

(it is sometimes hard to fight agains duplicated issues ...).
I am going to close this issue.

**Closed by Larpoux** 2021-01-18 14:52 UTC
Labels: New, maybe bug

**Comment by Larpoux** [comment] 2021-01-19 17:12
Could you try :
Flutter Sound 7.5.2+3

And watch for an error message : 
```
ERROR during registerWithRegistrar: flutterSoundPlayerManager == nil
```
or
```
ERROR during registerWithRegistrar: flutterSoundRecorderManager == nil
```

It is possible that you do not have crashes anymore, but if you get those messages during the Plugin initialization (before your first Player or Recorder instanciation), it will mean that there is still a serious bug.

Thank you for your cooperation.

**Comment by UttamPanchasara** [comment] 2021-01-20 04:59
Sure, thanks will check and update
